version: 0.2
env:
  variables:
    TERRAFORM_VERSION: 0.13.4

phases:
  pre_build:
    commands:
      - curl -o terraform_${TERRAFORM_VERSION}_linux_amd64.zip https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip
      - unzip -o terraform_${TERRAFORM_VERSION}_linux_amd64.zip && mv terraform /usr/bin
      - terraform --version
  
  build:
    commands:
      - terraform init
      - terraform plan
      # - terraform apply --auto-approve

  