version: 0.2
env:
  variables:
    TERRAFORM_VERSION: 0.13.4
phases:  
  install:
    commands:
      - export AWS_ACCESS_KEY_ID=$(AWS_ACCESS_KEY_ID)
      - export AWS_SECRET_ACCESS_KEY=$(AWS_SECRET_ACCESS_KEY)
      - curl -o terraform_${TERRAFORM_VERSION}_linux_amd64.zip https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip
      - unzip -o terraform_${TERRAFORM_VERSION}_linux_amd64.zip && mv terraform /usr/bin
      - terraform --version

  build:
    commands:
      - terraform init
      - terraform destroy --auto-approve

  